//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean TouchpadPressReset
        {
            get
            {
                return SteamVR_Actions.default_TouchpadPressReset;
            }
        }
        
        public virtual SteamVR_Action_Boolean Grab
        {
            get
            {
                return SteamVR_Actions.default_Grab;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean SideGrip
        {
            get
            {
                return SteamVR_Actions.default_SideGrip;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Boolean Menu
        {
            get
            {
                return SteamVR_Actions.default_Menu;
            }
        }
        
        public virtual SteamVR_Action_Boolean TouchpadUp
        {
            get
            {
                return SteamVR_Actions.default_TouchpadUp;
            }
        }
        
        public virtual SteamVR_Action_Boolean TouchpadDown
        {
            get
            {
                return SteamVR_Actions.default_TouchpadDown;
            }
        }
        
        public virtual SteamVR_Action_Boolean TouchPadLeft
        {
            get
            {
                return SteamVR_Actions.default_TouchPadLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean TouchPadRight
        {
            get
            {
                return SteamVR_Actions.default_TouchPadRight;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
